//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGlassDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.Photo = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int AdressId { get; set; }
        public int UserId { get; set; }
        public int ClaimStateId { get; set; }
        public string Description { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual ClaimState ClaimState { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
    }
}
